name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck action
        uses: koalaman/shellcheck-action@master
        with:
          files: |
            Main.sh
            Results.sh
